# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .public
    - mkdir -p .public/js/es/min/
    # Intentionally excludes sourcemaps.
    - cp -r dist/es/min/*.js .public/js/es/min/
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
